---
title: "Insect_Stats"
author: "Megan Rosser"
date: "2022-11-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

```{r read data}

insect_data <- read.csv("../data/identification.csv") %>%
  dplyr::mutate(level = str_extract(position, "^\\w")) %>%
  dplyr::mutate(position = str_extract(position, "(\\d\\w)")) %>%
  dplyr::mutate(position = as.factor(position)) %>%
  dplyr::mutate(level = as.factor(level)) %>%
  dplyr::mutate(date = as.factor(date)) 


```

```{r distinct data graph}
unique_insects <- insect_data %>%
  dplyr::select(order, family, morphospecies, level) %>%
  dplyr::distinct() %>%
  dplyr::mutate(order = as.factor(order)) %>%
  dplyr::mutate(order = factor(order, levels = c("siphonaptera", "psocodea", "acari", "araneae", "collembola", "coleoptera", "thysanoptera", "hemiptera", "hymenoptera", "diptera")))


unique_dodge <- ggplot2::ggplot(data = unique_insects) +
  geom_bar(aes(y = order,
               fill = level),
           position = position_dodge2()) +
  labs(y = "Order/Subclass",
       x = "# Morphospecies",
       fill = "Level") +
  scale_x_continuous(breaks = seq(0,20,4)) +
  scale_fill_manual(values = c("chartreuse2", "deepskyblue"),
                    labels = c("Ground", "Roof")) +
  theme_light()

unique_dodge

#ggsave("diversity_insect_plot1.png", path = "../figs")

```

```{r all data graph}
all_insects <- insect_data %>%
  dplyr::select(date, order, family, morphospecies, level) %>%
  dplyr::mutate(order = as.factor(order)) %>%
  dplyr::mutate(order = factor(order, levels = c("siphonaptera", "psocodea", "acari", "araneae", "collembola", "coleoptera", "thysanoptera", "hemiptera", "hymenoptera", "diptera"))) %>%
  dplyr::mutate(date = factor(date, levels = c("25-Jun", "10-Jul", "23-Jul", "7-Aug")))


all_dodge <- ggplot2::ggplot(data = all_insects) +
  geom_bar(aes(y = order,
               fill = level),
           position = position_dodge2()) +
  labs(y = "Order/Subclass",
       x = "# Observations",
       fill = "Level") +
  scale_x_continuous(breaks = seq(0,150,20), minor_breaks = waiver()) +
  scale_fill_manual(values = c("chartreuse2", "deepskyblue"),
                    labels = c("Ground", "Roof")) +
  theme_light()

all_dodge

#ggsave("abundance_insect_plot1.png", path = "../figs")

```

```{r proportion fill graph}

all_fill <- ggplot2::ggplot(data = all_insects) +
  geom_bar(aes(y = order,
               fill = level),
           position = position_fill()) +
  labs(y = "Class/Order") +
  theme_light()

all_fill

```

```{r time faceted abundance data, fig.width= 8, fig.height = 4}
all_dodge + facet_grid(cols = vars(date)) +
  theme_bw()

ggsave("abundance_date.png", width = 8, height = 4, path = "../figs")

unique_time_insects <- insect_data %>%
  dplyr::select(date, order, family, morphospecies, level) %>%
  dplyr::distinct() %>%
  dplyr::mutate(order = as.factor(order)) %>%
  dplyr::mutate(order = factor(order, levels = c("siphonaptera", "psocodea", "acari", "araneae", "collembola", "coleoptera", "thysanoptera", "hemiptera", "hymenoptera", "diptera"))) %>%
  dplyr::mutate(date = factor(date, levels = c("25-Jun", "10-Jul", "23-Jul", "7-Aug")))


unique_time_dodge <- ggplot2::ggplot(data = unique_time_insects) +
  geom_bar(aes(y = order,
               fill = level),
           position = position_dodge2()) +
  labs(y = "Order/Subclass",
       x = "# Morphospecies",
       fill = "Level") +
  scale_x_continuous(breaks = seq(0,20,4)) +
  scale_fill_manual(values = c("chartreuse2", "deepskyblue"),
                    labels = c("Ground", "Roof")) +
  theme_light()

unique_time_dodge + facet_grid(cols = vars(date)) +
  theme_bw()

ggsave("diversity_date.png", width = 8, height = 4, path = "../figs")

```



```{r all data}

insect_data %>%
  group_by(order) %>%
  summarise(family = n_distinct(family),
            morphospecies = n_distinct(morphospecies),
          .groups = "keep") %>%
  ungroup()


```


```{r ground level}
g_data <- insect_data %>%
  dplyr::filter(level == "G") %>%
  dplyr::rename(class_order = order)


g_data %>%
  group_by(class_order) %>%
  summarise(family = n_distinct(family),
            morphospecies = n_distinct(morphospecies),
          .groups = "keep") %>%
  ungroup()

```

```{r roof level}
r_data <- insect_data %>%
  dplyr::filter(level == "R") %>%
  dplyr::rename(class_order = order)

r_data %>%
  group_by(class_order) %>%
  summarise(families = n_distinct(family),
            morphospecies = n_distinct(morphospecies),
          .groups = "keep") %>%
  ungroup()

```



